# Generated by Django 4.2.10 on 2024-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_available'),
        ('users', '0002_balance_amount_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
