# Generated by Django 4.2.10 on 2024-08-16 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
